#!/usr/bin/env bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_shell_files() {
    declare -r CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "hushlogin"
        "init"

        "aliases"
        "plugins"
        "exports"
        "functions"
        "prompt"

        # "bash.local"  # For local settings that should
                      # not be under version control.
    )

    local file=""
    local i=""

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" \
        && . "../os/utils.sh"

    # shellcheck disable=SC2034
    declare -r OS="$(get_os)"
    echo "1 - Voici le dossier $OS pour les fichiers (°_°)"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # for i in ${!FILES_TO_SOURCE[*]}; do

    #     file="$HOME/.${FILES_TO_SOURCE[$i]}"


    #     [ -r "$file" ] \
    #         && . "$file"
    #     echo "2 - Voici le fichier $file exécuté (°_°)"

    # done

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$CURRENT_DIRECTORY"

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_shell_files
unset -f source_shell_files

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear system messages (system copyright notice, the date
# and time of the last login, the message of the day, etc.).

clear
