#!/usr/bin/env bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set LSCOLORS (FreeBSD / macOS).
#
#  * `ls` displays colors if the `-G` option is passed or if
#    the `CLICOLOR` environment variable is set.
#
#  * The actual colors are configured through the `LSCOLORS`
#    environment variable (built-in defaults are used if this
#    variable is not set).

LSCOLORS=""

LSCOLORS+="gx" # Directory
LSCOLORS+="fx" # Symbolic link
LSCOLORS+="cx" # Socket
LSCOLORS+="dx" # Pipe
LSCOLORS+="cx" # Executable
LSCOLORS+="eg" # Block special
LSCOLORS+="ed" # Character special
LSCOLORS+="ab" # Executable with setuid bit set
LSCOLORS+="ag" # Executable with setgid bit set
LSCOLORS+="cc" # Directory writable to others, with sticky bit
LSCOLORS+="bd" # Directory writable to others, without sticky bit

export LSCOLORS

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Enable color support.

alias ls="ls -G"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Colored manpages with tcsh

export LESS_TERMCAP_mb=$'\E[01;36m' # begin blinking
export LESS_TERMCAP_md=$'\E[01;36m' # begin bold
export LESS_TERMCAP_me=$'\E[0m' # end mode
export LESS_TERMCAP_se=$'\E[0m' # end standout-mode
export LESS_TERMCAP_so=$'\E[01;44;32m' # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m' # end underline
export LESS_TERMCAP_us=$'\E[01;35m' # begin underline

# # Colorcodes:

# # Black       0;30     Dark Gray     1;30
# # Red         0;31     Light Red     1;31
# # Green       0;32     Light Green   1;32
# # Brown       0;33     Yellow        1;33
# # Blue        0;34     Light Blue    1;34
# # Purple      0;35     Light Purple  1;35
# # Cyan        0;36     Light Cyan    1;36
# # Light Gray  0;37     White         1;37
