#!/usr/bin/env bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set LSCOLORS (FreeBSD / macOS).
#
#  * `ls` displays colors if the `-G` option is passed or if
#    the `CLICOLOR` environment variable is set.
#
#  * The actual colors are configured through the `LSCOLORS`
#    environment variable (built-in defaults are used if this
#    variable is not set).

LSCOLORS=""

LSCOLORS+=$(tput setaf 2; tput setab 0)  # Directory - Green text on black background
LSCOLORS+=$(tput setaf 4; tput setab 0)  # Symbolic link - Blue text on black background
LSCOLORS+=$(tput setaf 6; tput setab 0)  # Socket - Cyan text on black background
LSCOLORS+=$(tput setaf 3; tput setab 0)  # Pipe - Yellow text on black background
LSCOLORS+=$(tput setaf 1; tput setab 0)  # Executable - Red text on black background
LSCOLORS+=$(tput setaf 2; tput setab 0)  # Block special - Green text on black background
LSCOLORS+=$(tput setaf 1; tput setab 0)  # Character special - Red text on black background
LSCOLORS+=$(tput setaf 3; tput setab 0)  # Executable with setuid bit set - Yellow text on black background
LSCOLORS+=$(tput setaf 2; tput setab 0)  # Executable with setgid bit set - Green text on black background
LSCOLORS+=$(tput setaf 6; tput setab 0)  # Directory writable to others, with sticky bit - Cyan text on black background
LSCOLORS+=$(tput setaf 1; tput setab 0)  # Directory writable to others, without sticky bit - Red text on black background

export LSCOLORS

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Enable color support.

alias ls="ls -G"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Colored manpages with tcsh

export LESS_TERMCAP_mb=$(tput setaf 6)  # begin blinking - Cyan
export LESS_TERMCAP_md=$(tput setaf 6)  # begin bold - Cyan
export LESS_TERMCAP_me=$(tput sgr0)     # end mode
export LESS_TERMCAP_se=$(tput sgr0)     # end standout-mode
export LESS_TERMCAP_so=$(tput setab 4; tput setaf 2)  # begin standout-mode - info box - Green background, Black text
export LESS_TERMCAP_ue=$(tput sgr0)     # end underline
export LESS_TERMCAP_us=$(tput setaf 5)  # begin underline - Purple

# Text in color:
# tput setaf N: Sets the foreground text color, where N is the color code (0-7).
# tput sgr0: Resets the text color to the default.

# Colored background:
# tput setab N: Sets the background color, where N is the color code (0-7).

# Text styles:
# tput bold: Bold text.
# tput dim: Text with reduced intensity.
# tput smul: Underlined text.
# tput rev: Video reverse (swaps text and background).
# tput smso: Standout video mode (standout).

# Here is a list of standard color codes:
# 0: Black
# 1: Red
# 2: Green
# 3: Yellow
# 4: Blue
# 5: Magenta
# 6: Cyan
# 7: White
