#!/usr/bin/env bash

# `o` with no arguments opens the current directory, otherwise opens the given
# location
o() {
	if [ $# -eq 0 ]; then
		open .;
	else
		open "$@";
	fi;
}

# Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
update() {
    # Check if Homebrew is installed
    if ! command -v brew &> /dev/null; then
        printf "Error: Homebrew is not installed. Please install Homebrew and try again.\n"
        exit 1
    fi

    # Homebrew updates
    printf "\n%s\n" "------------------------------------------------------------------------"
    printf "• brew update"
    printf "\n%s\n" "------------------------------------------------------------------------"
    brew update && printf "\n"

    printf "\n%s\n" "------------------------------------------------------------------------"
    printf "• brew upgrade"
    printf "\n%s\n" "------------------------------------------------------------------------"
    brew upgrade && printf "\n"

    printf "\n%s\n" "------------------------------------------------------------------------"
    printf "• brew cleanup"
    printf "\n%s\n" "------------------------------------------------------------------------"
    brew cleanup && printf "\n"

    printf "\n%s\n" "------------------------------------------------------------------------"
    printf "• brew doctor"
    printf "\n%s\n" "------------------------------------------------------------------------"
    brew doctor && printf "\n"

    # System updates
    printf "\n%s\n" "------------------------------------------------------------------------"
    printf "• softwareupdate"
    printf "\n%s\n" "------------------------------------------------------------------------"
    sudo softwareupdate -i -a && printf "\n"

    # Check if Node.js is installed
    if ! command -v node &> /dev/null; then
        printf "Error: Node.js is not installed. Please install Node.js and try again.\n"
        exit 1
    fi

    # Node.js updates
    printf "\n%s\n" "------------------------------------------------------------------------"
    printf "• npm install npm@latest -g"
    printf "\n%s\n" "------------------------------------------------------------------------"
    npm install npm@latest -g && printf "\n"

    printf "\n%s\n" "------------------------------------------------------------------------"
    printf "• npm update -g"
    printf "\n%s\n" "------------------------------------------------------------------------"
    npm update -g && printf "\n"
}

