#!/usr/bin/env bash

# `o` with no arguments opens the current directory, otherwise opens the given
# location
o() {
	if [ $# -eq 0 ]; then
		open .;
	else
		open "$@";
	fi;
}

# Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
update() {
    # Check if Homebrew is installed
    if ! command -v brew &> /dev/null; then
        echo "Error: Homebrew is not installed. Please install Homebrew and try again."
        exit 1
    fi

    # Homebrew updates
    echo "------------------------------------------------------------------------"
    echo "brew update"
    echo "------------------------------------------------------------------------"
    brew update && echo ""

    echo "------------------------------------------------------------------------"
    echo "brew upgrade"
    echo "------------------------------------------------------------------------"
    brew upgrade && echo ""

    echo "------------------------------------------------------------------------"
    echo "brew cleanup"
    echo "------------------------------------------------------------------------"
    brew cleanup && echo ""

    echo "------------------------------------------------------------------------"
    echo "brew doctor"
    echo "------------------------------------------------------------------------"
    brew doctor && echo ""

    # System updates
    echo "------------------------------------------------------------------------"
    echo "softwareupdate"
    echo "------------------------------------------------------------------------"
    sudo softwareupdate -i -a && echo ""

    # Check if Node.js is installed
    if ! command -v node &> /dev/null; then
        echo "Error: Node.js is not installed. Please install Node.js and try again."
        exit 1
    fi

    # Node.js updates
    echo "------------------------------------------------------------------------"
    echo "npm install npm@latest -g"
    echo "------------------------------------------------------------------------"
    npm install npm@latest -g && echo ""

    echo "------------------------------------------------------------------------"
    echo "npm update -g"
    echo "------------------------------------------------------------------------"
    npm update -g && echo ""
}
